### ISSUE TITLE
No GUI access

### ISSUE THREAD

**Issue by b4b857f6ee** [VultureProject/vulture-base#2] opened 2019-06-20 13:14 UTC
Hi,
I just install the 0.2rc with the ovf and on a clean freebsd 12.0
I got the same issue for both.
When i configure the hostname in admin menu i see for all jail, not found.
For the management IP modification nothing change. The Readme say "*" " this command will run installation & configuration  of jails" 
I have some logs for update OS or Hostname menu but nothing for Management.
Any idea?
I have done pkg update and upgrade for both VM.

**Comment by b4b857f6ee** [comment] 2019-06-20 13:32
I manage to get the access for the clean freebsd install. I have use hostname command to get a certificat.
I have add jail_enable="YES" in /etc/rc.conf even if service jail status work.
And run 2 time /home/vlt-adm/gui/cluster_create.sh as root

**Comment by b4b857f6ee** [comment] 2019-06-20 17:34
#Other subject : Add to the readme : do not use 192.168.1.0/24 network or you can have conflict with the vm-public interface by default in 192.168.1.1

**Comment by b4b857f6ee** [comment] 2019-06-20 17:50
For the complet process to get the GUI from a clean FreeBSD install you need to add the information that we need to run the "hostname" command after install all the jail to get the certificat generation and the start up of all services/jail.

**Comment by hashimea** [comment] 2019-07-06 15:13
@b4b857f6ee Could you please explain the things done. I followed the readme for installing on fresh freebsd12. Unable to get the gui working.

**Comment by b4b857f6ee** [comment] 2019-07-06 20:48
Yeh, did you install a FreeBSD12 amd64 ?

**Comment by hashimea** [comment] 2019-07-07 05:21
@b4b857f6ee Yes. I used FreeBSD-12.0-RELEASE-amd64-dvd1.iso with ZFS.
Till package installation everything was fine. But after that getting errors like above.

**Comment by b4b857f6ee** [comment] 2019-07-07 14:28
Ok, i remember i got the same problem... i didn't remember well but i think it's something like your pkg configuration are not in amd64. something like that.

**Comment by hashimea** [comment] 2019-07-07 14:39
ok. Thanks for the clue. Also whether the learning mode working? I mean whether the dataset logs is getting recorded for application for creating rules.

**Comment by b4b857f6ee** [comment] 2019-07-07 14:49
I can check if i still have the VM tomorrow.
I didn't check it yet. I stop trying and waiting others versions because my Vulture crash when i running wss request :/. But it's a beta version so .. :)

**Comment by hashimea** [comment] 2019-07-07 15:02
:) Its ok. Also, let me know whether that worked with the stable one.  Vulture 3 on freebsd12

**Comment by b4b857f6ee** [comment] 2019-07-11 07:38
@hashimea did you succeed to install it?

**Comment by hashimea** [comment] 2019-07-13 05:26
@b4b857f6ee Not yet

**Comment by KGuillemot** [comment] 2019-07-23 15:49
> @b4b857f6ee Could you please explain the things done. I followed the readme for installing on fresh freebsd12. Unable to get the gui working.
> 
> Getting the following error when bootstraping system jails
> 
> `Updating FreeBSD repository catalogue... pkg: http://pkg.FreeBSD.org/FreeBSD:12:amd64/quarterly/meta.txz: No address record repository FreeBSD has no meta file, using default settings pkg: http://pkg.FreeBSD.org/FreeBSD:12:amd64/quarterly/packagesite.txz: No address record Unable to update repository FreeBSD Error updating repositories! Fail ! `

Hello,

If you have this error, it's probably because the NAT is not done correctly by PF and your jails cannot access internet. Try to execute : 
`pfctl -snat` and verify if the nat address has access to internet.
It's hard to explain, don't hesitate do ask if I'm not clear.
Regards,

Kevin

**Comment by hashimea** [comment] 2019-08-14 08:10
@KGuillemot Everything working fine after installation. 
But after rebooting the system unable to load the gui. I am getting the 504 error

> Gateway Timeout
> The gateway did not receive a timely response from the upstream server or application.

**Comment by hashimea** [comment] 2019-08-14 10:46
> @KGuillemot Everything working fine after installation.
> But after rebooting the system unable to load the gui. I am getting the 504 error
> 
> > Gateway Timeout
> > The gateway did not receive a timely response from the upstream server or application.

Issue is with vm. The vmm kernel module which is needed for inside vm not loading. I am using the freebsd kvm with proxmox host. Nested virtualization enabled but still the module is not working.

**Comment by jjourdin** [comment] 2019-09-18 13:30
Hi, closing this issue - not reproductable on latest release.
Nested virtualization is not mandatory for the community version of Vulture4. Vulture will complain about vmm not being available at boot time, but everything will work as expected (except virtualisation, of course).

**Closed by jjourdin** 2019-09-18 13:30 UTC

**Comment by ErrafayM** [comment] 2020-06-04 12:12
> #Other subject : Add to the readme : do not use 192.168.1.0/24 network or you can have conflict with the vm-public interface by default in 192.168.1.1

Can the default vm-public 192.168.1.1 be changed?
